// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using PowerPointRemote.WebAPI.Data;

namespace PowerPointRemote.WebApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    internal class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PowerPointRemote.WebApi.Models.EntityFramework.Channel", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("char(9)");

                b.Property<bool>("ChannelEnded")
                    .HasColumnType("tinyint(1)");

                b.Property<int>("CurrentSlidePosition")
                    .HasColumnType("int");

                b.Property<DateTime>("LastUpdate")
                    .HasColumnType("datetime(6)");

                b.Property<int>("SlideCount")
                    .HasColumnType("int");

                b.Property<bool>("SlideShowStarted")
                    .HasColumnType("tinyint(1)");

                b.HasKey("Id");

                b.ToTable("Channels");
            });

            modelBuilder.Entity("PowerPointRemote.WebApi.Models.EntityFramework.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<string>("ChannelId")
                    .IsRequired()
                    .HasColumnType("char(9)");

                b.Property<int>("Connections")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                    .HasMaxLength(255);

                b.HasKey("Id");

                b.HasIndex("ChannelId");

                b.ToTable("Users");
            });

            modelBuilder.Entity("PowerPointRemote.WebApi.Models.EntityFramework.User", b =>
            {
                b.HasOne("PowerPointRemote.WebApi.Models.EntityFramework.Channel", "Channel")
                    .WithMany("Users")
                    .HasForeignKey("ChannelId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}